@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFuZHJlc2dvbWV6QGdtYWlsLmNvbSIsImlhdCI6MTc4OTQ5MDQzOCwiZXhwIjoxNzg5NTc2ODM4fQ.BGf26or2u0VbtfkU4dipcR8wp-h-lHnT7Ke8gFEz-Z0

### Listar todos los departamentos
GET http://localhost:3000/api/department
Authorization: Bearer {{token}}


###

### Buscar departamento por nombre
GET http://localhost:3000/api/department/Sistemas
Authorization: Bearer {{token}}

###

### Crear departamento
POST http://localhost:3000/api/department
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Sistemas"
}


###

### Eliminar departamento por ID
DELETE http://localhost:3000/api/department/6
Authorization: Bearer {{token}}


###

### Actualizar departamento
PATCH http://localhost:3000/api/department/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Tecnologia"
}