@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhcmxvc0B0ZXN0LmNvbSIsImlkX3JvbCI6bnVsbCwiaWF0IjoxNzg5NTI1ODg1LCJleHAiOjE3ODk1MzMwODV9.TsGvNOaKTgebu6llJeS191YlNKAuUy02gseRXyuV2HE

### Get all roles
GET http://localhost:3000/api/role
Authorization: Bearer {{token}}


###

### Search role by name
GET http://localhost:3000/api/role/Administrator
Authorization: Bearer {{token}}



###

### Create role
POST http://localhost:3000/api/role
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "name": "Administrator"
}


###

### Delete role by ID
DELETE http://localhost:3000/api/role/6
Authorization: Bearer {{token}}


###

### Update role
PATCH http://localhost:3000/api/role/1
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "name": "admin"
}